import { cp, mkdir, mkdtemp, readFile, rename, writeFile } from "node:fs/promises";
import { delimiter, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { compile, getNamespaceFullName, listServices, logDiagnostics, NodeHost } from "@typespec/compiler";
import { parse } from "yaml";

const root = fileURLToPath(new URL("../", import.meta.url));
const config = parse(await readFile(join(root, "tspconfig.yaml"), "utf8"));
const emitters = {
  csharp: "@typespec/http-client-csharp",
  java: "@typespec/http-client-java",
  python: "@typespec/http-client-python",
  javascript: "@azure-tools/typespec-ts",
};
const languages = process.argv.length > 2 ? process.argv.slice(2) : Object.keys(emitters);
for (const language of languages) {
  if (!Object.hasOwn(emitters, language)) throw new Error(`Unknown language: ${language}`);
}
// The Java emitter launches java/javac/mvn using PATH, not JAVA_HOME/MAVEN_HOME.
process.env.PATH = [process.env.JAVA_HOME, process.env.MAVEN_HOME]
  .filter(Boolean).map((home) => join(home, "bin")).concat(process.env.PATH ?? "").join(delimiter);

await mkdir(join(root, "tsp-output"), { recursive: true });
const staging = await mkdtemp(join(root, "tsp-output", "clients-"));
const source = join(root, "client.tsp");
const contract = await compile(NodeHost, source, { noEmit: true });
check(contract);
const services = listServices(contract).map((service) => getNamespaceFullName(service.type)).sort();

for (const language of languages) {
  const emitter = emitters[language];
  const output = join(staging, language);
  const options = { ...config.options[emitter], "emitter-output-dir": output };
  if (language === "javascript") {
    const exports = [];
    // One explicit client per compilation avoids the official TS emitter's multi-service
    // context type collision. HTTP methods/models remain entirely emitter-generated.
    for (const service of services) {
      const name = service.split(".").slice(1).join("");
      const folder = service.toLowerCase().replaceAll(".", "-");
      const entry = join(staging, "client.tsp");
      await writeFile(entry, `import ${JSON.stringify(source.replaceAll("\\", "/"))};\n`
        + `@Azure.ClientGenerator.Core.client({service: ${service}, name: "${name}Client", autoMergeService: true})\n`
        + "namespace SelectedClient {}\n");
      const serviceOutput = join(staging, "services", folder);
      await emit(entry, emitter, { ...options, "generate-metadata": false,
        "emitter-output-dir": serviceOutput });
      await cp(join(serviceOutput, "src"), join(output, "services", folder, "src"), { recursive: true });
      exports.push(`export * as ${name} from "./services/${folder}/src/index.js";`);
      console.log(`Generated JavaScript/TypeScript: ${service}`);
    }
    await writeFile(join(output, "index.ts"), "// Generated by tools/generate-clients.mjs.\n" + exports.join("\n") + "\n");
  } else {
    await emit(source, emitter, options);
  }
  if (language === "csharp" || language === "javascript" || language === "python") {
    await cp(join(root, "tools", "client-packaging", language), output, { recursive: true });
  }
  await cp(join(root, "LICENSE"), join(output, "LICENSE"));
  await writeFile(join(output, "services.json"), JSON.stringify({ emitter, services }, null, 2) + "\n");
  // Retain the previous output in the ignored staging directory. Only replace a
  // language's SDK after its entire generation has succeeded.
  const destination = resolve(root, "generated", "clients", language);
  await mkdir(join(root, "generated", "clients"), { recursive: true });
  try { await rename(destination, join(staging, `previous-${language}`)); }
  catch (error) { if (error.code !== "ENOENT") throw error; }
  await rename(output, destination);
  console.log(`Generated ${language}: ${destination} (${services.length} services)`);
}

async function emit(entry, emitter, options) {
  check(await compile(NodeHost, entry, { emit: [emitter], options: { [emitter]: options }, outputDir: staging }));
}

function check(program) {
  const diagnostics = program.diagnostics.filter((d) =>
    d.code !== "@azure-tools/typespec-ts/property-name-normalized");
  logDiagnostics(diagnostics, NodeHost.logSink);
  if (program.hasError()) throw new Error("Client generation failed; see TypeSpec diagnostics above.");
}
