import { cp, mkdir, mkdtemp, readFile, readdir, rename, rm, writeFile } from "node:fs/promises";
import { delimiter, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { compile, getNamespaceFullName, listServices, logDiagnostics, NodeHost } from "@typespec/compiler";
import { parse } from "yaml";

const root = fileURLToPath(new URL("../", import.meta.url));
const config = parse(await readFile(join(root, "tspconfig.yaml"), "utf8"));
const emitters = {
  csharp: "@typespec/http-client-csharp",
  java: "@typespec/http-client-java",
  python: "@typespec/http-client-python",
  javascript: "@azure-tools/typespec-ts",
  rust: "@azure-tools/typespec-rust",
};
const languagesWithDsRuntime = new Set(["csharp", "java", "python", "javascript", "rust"]);
const languages = process.argv.length > 2 ? process.argv.slice(2) : Object.keys(emitters);
for (const language of languages) {
  if (!Object.hasOwn(emitters, language)) throw new Error(`Unknown language: ${language}`);
}
// The Java emitter launches java/javac/mvn using PATH, not JAVA_HOME/MAVEN_HOME.
process.env.PATH = [process.env.JAVA_HOME, process.env.MAVEN_HOME]
  .filter(Boolean).map((home) => join(home, "bin")).concat(process.env.PATH ?? "").join(delimiter);

await mkdir(join(root, "tsp-output"), { recursive: true });
const staging = await mkdtemp(join(root, "tsp-output", "clients-"));
const source = join(root, "client.tsp");
const contract = await compile(NodeHost, source, { noEmit: true });
check(contract);
const services = listServices(contract).map((service) => getNamespaceFullName(service.type)).sort();
const needsDsRuntime = languages.some((language) => languagesWithDsRuntime.has(language));
const dsGenerations = needsDsRuntime ? await readDsGenerations(await emitDsManifest()) : undefined;
// DS remains a required wire-contract header. SDK emitters receive an isolated
// source copy with it optional so their send pipelines can add it when omitted.
const dsSource = needsDsRuntime ? await createDsOptionalSource() : source;

for (const language of languages) {
  const emitter = emitters[language];
  const output = join(staging, language);
  const options = { ...config.options[emitter], "emitter-output-dir": output };
  if (language === "rust") {
    // The Rust emitter inherits every manifest field from a Cargo workspace and runs
    // `cargo fmt` in its output directory afterwards. Pre-seeding the packaged
    // manifest keeps the emitter from writing one it cannot format.
    await mkdir(output, { recursive: true });
    await cp(join(root, "tools", "client-packaging", "rust", "Cargo.toml"), join(output, "Cargo.toml"));
  }
  if (language === "javascript") {
    const exports = [];
    // One explicit client per compilation avoids the official TS emitter's multi-service
    // context type collision. HTTP methods/models remain entirely emitter-generated.
    for (const service of services) {
      const name = service.split(".").slice(1).join("");
      const folder = service.toLowerCase().replaceAll(".", "-");
      const entry = join(staging, "client.tsp");
      await writeFile(entry, `import ${JSON.stringify(dsSource.replaceAll("\\", "/"))};\n`
        + `@Azure.ClientGenerator.Core.client({service: ${service}, name: "${name}Client", autoMergeService: true})\n`
        + "namespace SelectedClient {}\n");
      const serviceOutput = join(staging, "services", folder);
      await emit(entry, emitter, { ...options, "generate-metadata": false,
        "emitter-output-dir": serviceOutput });
      await cp(join(serviceOutput, "src"), join(output, "services", folder, "src"), { recursive: true });
      exports.push(`export * as ${name} from "./services/${folder}/src/index.js";`);
      console.log(`Generated JavaScript/TypeScript: ${service}`);
    }
    await writeFile(join(output, "index.ts"), "// Generated by tools/generate-clients.mjs.\nexport * from \"./ds.js\";\nexport * from \"./dsPolicy.js\";\n" + exports.join("\n") + "\n");
  } else {
    await emit(dsSource, emitter, options);
  }
  if (languagesWithDsRuntime.has(language)) {
    await cp(join(root, "tools", "client-packaging", language), output, { recursive: true });
  }
  if (language === "javascript") await cp(join(root, "runtime", "ds.ts"), join(output, "ds.ts"));
  if (language === "csharp") {
    await writeCsharpDsOperationMap(dsGenerations, join(output, "src", "DsOperationMap.cs"));
    await assertCsharpServiceClients(output, services);
  }
  if (language === "java") await writeJavaDsOperationMap(dsGenerations, output);
  if (language === "python") await writePythonDsOperationMap(dsGenerations, output);
  if (language === "javascript") await writeJavaScriptDsOperationMap(dsGenerations, output);
  if (language === "rust") await writeRustDsOperationMap(dsGenerations, output);
  await cp(join(root, "LICENSE"), join(output, "LICENSE"));
  await writeFile(join(output, "services.json"), JSON.stringify({ emitter, services }, null, 2) + "\n");
  // Retain the previous output in the ignored staging directory. Only replace a
  // language's SDK after its entire generation has succeeded.
  const destination = resolve(root, "generated", "clients", language);
  await mkdir(join(root, "generated", "clients"), { recursive: true });
  let synchronizedInPlace = false;
  try { await rename(destination, join(staging, `previous-${language}`)); }
  catch (error) {
    if (error.code === "EPERM" || error.code === "EBUSY") {
      // Windows can temporarily deny directory renames while an IDE or scanner has a file open.
      // Keep the atomic replacement path as the default, but preserve a complete output tree in this case.
      await mirrorDirectory(output, destination);
      synchronizedInPlace = true;
    } else if (error.code !== "ENOENT") {
      throw error;
    }
  }
  if (!synchronizedInPlace) await rename(output, destination);
  console.log(`Generated ${language}: ${destination} (${services.length} services)`);
}

async function emit(entry, emitter, options) {
  check(await compile(NodeHost, entry, { emit: [emitter], options: { [emitter]: options }, outputDir: staging }));
}

async function emitDsManifest() {
  const output = join(staging, "csharp-ds-manifest");
  await emit(join(root, "main.tsp"), "@uigf/typespec-ds", { "emitter-output-dir": output });
  return join(output, "ds-manifest.json");
}

async function createDsOptionalSource() {
  const directory = join(staging, "ds-optional-source");
  await cp(join(root, "src"), join(directory, "src"), { recursive: true });
  await cp(join(root, "main.tsp"), join(directory, "main.tsp"));
  await cp(source, join(directory, "client.tsp"));

  for (const entry of await readdir(join(directory, "src"), { withFileTypes: true })) {
    if (!entry.isFile() || !entry.name.endsWith(".tsp")) continue;
    const path = join(directory, "src", entry.name);
    const text = await readFile(path, "utf8");
    const optionalDs = text
      .replaceAll('@header("DS") ds: string', '@header("DS") ds?: string')
      .replace(/(@header\("DS"\)\s*\r?\n\s*)ds: string;/g, "$1ds?: string;");
    if (optionalDs !== text) await writeFile(path, optionalDs);
  }
  return join(directory, "client.tsp");
}

function check(program) {
  const diagnostics = program.diagnostics.filter((d) =>
    d.code !== "@azure-tools/typespec-ts/property-name-normalized");
  logDiagnostics(diagnostics, NodeHost.logSink);
  if (program.hasError()) throw new Error("Client generation failed; see TypeSpec diagnostics above.");
}

async function mirrorDirectory(source, destination) {
  await mkdir(destination, { recursive: true });
  const [sourceEntries, destinationEntries] = await Promise.all([
    readdir(source, { withFileTypes: true }),
    readdir(destination, { withFileTypes: true }),
  ]);
  const sourceByName = new Map(sourceEntries.map((entry) => [entry.name, entry]));

  for (const entry of destinationEntries) {
    if (!sourceByName.has(entry.name)) {
      await rm(join(destination, entry.name), { recursive: true, force: true });
    }
  }

  for (const entry of sourceEntries) {
    const sourcePath = join(source, entry.name);
    const destinationPath = join(destination, entry.name);
    if (entry.isDirectory()) {
      const destinationEntry = destinationEntries.find((candidate) => candidate.name === entry.name);
      if (destinationEntry && !destinationEntry.isDirectory()) {
        await rm(destinationPath, { force: true });
      }
      await mirrorDirectory(sourcePath, destinationPath);
    } else {
      const destinationEntry = destinationEntries.find((candidate) => candidate.name === entry.name);
      if (destinationEntry?.isDirectory()) {
        await rm(destinationPath, { recursive: true, force: true });
      }
      await cp(sourcePath, destinationPath, { force: true });
    }
  }
}

async function readDsGenerations(manifestPath) {
  const manifest = JSON.parse(await readFile(manifestPath, "utf8"));
  const generations = new Map();
  for (const service of manifest.services) {
    for (const operation of service.operations) {
      const generation = operation.generation === "v1" ? "V1" : "V2";
      const previous = generations.get(operation.path);
      if (previous && previous !== generation) {
        throw new Error(`DS generation mismatch for ${operation.path}.`);
      }
      generations.set(operation.path, generation);
    }
  }

  return generations;
}

async function writeCsharpDsOperationMap(generations, outputPath) {
  const cases = [...generations.entries()].sort(([left], [right]) => left.localeCompare(right))
    .map(([path, generation]) => `                case "${path}":\n                    generation = DsGeneration.${generation};\n                    return true;`)
    .join("\n");
  const source = `// <auto-generated/>\n\n#nullable enable\n\nnamespace UIGF.Mihoyo\n{\n    internal static class DsOperationMap\n    {\n        internal static bool TryGetGeneration(string path, out DsGeneration generation)\n        {\n            switch (path)\n            {\n${cases}\n                default:\n                    generation = default;\n                    return false;\n            }\n        }\n    }\n}\n`;
  await writeFile(outputPath, source);
}

async function writeJavaScriptDsOperationMap(generations, output) {
  const entries = [...generations.entries()].sort(([left], [right]) => left.localeCompare(right))
    .map(([path, generation]) => `  [${JSON.stringify(path)}, ${generation === "V1" ? 1 : 2}],`)
    .join("\n");
  await writeFile(join(output, "dsOperationMap.ts"), `// <auto-generated/>\n\nexport const dsGenerations: ReadonlyMap<string, 1 | 2> = new Map([\n${entries}\n]);\n`);
}

async function writePythonDsOperationMap(generations, output) {
  const directory = join(output, "uigf", "mihoyo");
  await mkdir(directory, { recursive: true });
  const entries = [...generations.entries()].sort(([left], [right]) => left.localeCompare(right))
    .map(([path, generation]) => `    ${JSON.stringify(path)}: ${generation === "V1" ? 1 : 2},`)
    .join("\n");
  await writeFile(join(directory, "_ds_operation_map.py"), `# <auto-generated/>\n\nDS_GENERATIONS: dict[str, int] = {\n${entries}\n}\n`);
}

async function writeJavaDsOperationMap(generations, output) {
  const directory = join(output, "src", "main", "java", "uigf", "mihoyo");
  await mkdir(directory, { recursive: true });
  const cases = [...generations.entries()].sort(([left], [right]) => left.localeCompare(right))
    .map(([path, generation]) => `            case ${JSON.stringify(path)}:\n                return ${generation === "V1" ? 1 : 2};`)
    .join("\n");
  await writeFile(join(directory, "DsOperationMap.java"), `// <auto-generated/>\n\npackage uigf.mihoyo;\n\nfinal class DsOperationMap {\n    private DsOperationMap() {}\n\n    static int getGeneration(String path) {\n        switch (path) {\n${cases}\n            default:\n                return 0;\n        }\n    }\n}\n`);
}

async function writeRustDsOperationMap(generations, output) {
  const directory = join(output, "src");
  await mkdir(directory, { recursive: true });
  const arms = [...generations.entries()].sort(([left], [right]) => left.localeCompare(right))
    .map(([path, generation]) => `        ${JSON.stringify(path)} => Some(DsGeneration::${generation}),`)
    .join("\n");
  const map = `// <auto-generated/>\n\nuse crate::ds::DsGeneration;\n\n/// Returns the Dynamic Secret payload layout required by a request path.\npub(crate) fn generation(path: &str) -> Option<DsGeneration> {\n    match path {\n${arms}\n        _ => None,\n    }\n}\n`;
  await writeFile(join(directory, "ds_operation_map.rs"), map);

  // The emitter owns `lib.rs`, so the DS modules are appended after generation.
  const libRs = join(directory, "lib.rs");
  await writeFile(libRs, `${await readFile(libRs, "utf8")}\nmod ds_operation_map;\npub mod ds;\n`);
}

async function assertCsharpServiceClients(output, services) {
  const generated = join(output, "src", "Generated");
  const files = await readdir(generated, { withFileTypes: true });
  const namespaces = new Set();
  const typesByNamespace = new Map();
  const rootClients = [];

  for (const file of files) {
    if (!file.isFile() || !file.name.endsWith(".cs") || file.name.endsWith(".RestClient.cs")) continue;
    const source = await readFile(join(generated, file.name), "utf8");
    const namespace = source.match(/^namespace\s+([\w.]+)\s*$/m)?.[1];
    const type = source.match(/\bpublic\s+partial\s+class\s+(\w+)\b/)?.[1];
    if (!namespace || !type) continue;

    if (!typesByNamespace.has(namespace)) typesByNamespace.set(namespace, new Set());
    typesByNamespace.get(namespace).add(type);
    if (file.name.endsWith("Client.cs")) {
      namespaces.add(namespace);
      rootClients.push({ namespace, source });
    }
  }

  const missing = services.filter((service) => !namespaces.has(service));
  if (missing.length > 0) {
    throw new Error(`C# generation did not expose a public root client for: ${missing.join(", ")}`);
  }

  const missingOperationGroups = rootClients.flatMap(({ namespace, source }) =>
    [...source.matchAll(/private\s+(\w+)\s+_cached\w+;/g)]
      .map((match) => `${namespace}.${match[1]}`)
      .filter((type) => !typesByNamespace.get(namespace).has(type.slice(namespace.length + 1))));
  if (missingOperationGroups.length > 0) {
    throw new Error(`C# generation did not expose operation groups for: ${missingOperationGroups.join(", ")}`);
  }
}
