import { cp, mkdir, mkdtemp, readFile, readdir, rename, rm, writeFile } from "node:fs/promises";
import { delimiter, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { compile, getNamespaceFullName, listServices, logDiagnostics, NodeHost } from "@typespec/compiler";
import { parse } from "yaml";

const root = fileURLToPath(new URL("../", import.meta.url));
const config = parse(await readFile(join(root, "tspconfig.yaml"), "utf8"));
const emitters = {
  csharp: "@typespec/http-client-csharp",
  java: "@typespec/http-client-java",
  python: "@typespec/http-client-python",
  javascript: "@azure-tools/typespec-ts",
};
const languages = process.argv.length > 2 ? process.argv.slice(2) : Object.keys(emitters);
for (const language of languages) {
  if (!Object.hasOwn(emitters, language)) throw new Error(`Unknown language: ${language}`);
}
// The Java emitter launches java/javac/mvn using PATH, not JAVA_HOME/MAVEN_HOME.
process.env.PATH = [process.env.JAVA_HOME, process.env.MAVEN_HOME]
  .filter(Boolean).map((home) => join(home, "bin")).concat(process.env.PATH ?? "").join(delimiter);

await mkdir(join(root, "tsp-output"), { recursive: true });
const staging = await mkdtemp(join(root, "tsp-output", "clients-"));
const source = join(root, "client.tsp");
const contract = await compile(NodeHost, source, { noEmit: true });
check(contract);
const services = listServices(contract).map((service) => getNamespaceFullName(service.type)).sort();
const csharpDsManifest = languages.includes("csharp") ? await emitDsManifest() : undefined;
// DS remains a required wire-contract header. The C# emitter alone receives an
// isolated source copy with it optional, allowing its convenience overloads to
// defer signing to DsSigningPolicy without loosening the other SDKs' surfaces.
const csharpSource = languages.includes("csharp") ? await createCsharpSource() : undefined;

for (const language of languages) {
  const emitter = emitters[language];
  const output = join(staging, language);
  const options = { ...config.options[emitter], "emitter-output-dir": output };
  if (language === "javascript") {
    const exports = [];
    // One explicit client per compilation avoids the official TS emitter's multi-service
    // context type collision. HTTP methods/models remain entirely emitter-generated.
    for (const service of services) {
      const name = service.split(".").slice(1).join("");
      const folder = service.toLowerCase().replaceAll(".", "-");
      const entry = join(staging, "client.tsp");
      await writeFile(entry, `import ${JSON.stringify(source.replaceAll("\\", "/"))};\n`
        + `@Azure.ClientGenerator.Core.client({service: ${service}, name: "${name}Client", autoMergeService: true})\n`
        + "namespace SelectedClient {}\n");
      const serviceOutput = join(staging, "services", folder);
      await emit(entry, emitter, { ...options, "generate-metadata": false,
        "emitter-output-dir": serviceOutput });
      await cp(join(serviceOutput, "src"), join(output, "services", folder, "src"), { recursive: true });
      exports.push(`export * as ${name} from "./services/${folder}/src/index.js";`);
      console.log(`Generated JavaScript/TypeScript: ${service}`);
    }
    await writeFile(join(output, "index.ts"), "// Generated by tools/generate-clients.mjs.\n" + exports.join("\n") + "\n");
  } else {
    await emit(language === "csharp" ? csharpSource : source, emitter, options);
  }
  if (language === "csharp" || language === "javascript" || language === "python") {
    await cp(join(root, "tools", "client-packaging", language), output, { recursive: true });
  }
  if (language === "csharp") {
    await writeCsharpDsOperationMap(csharpDsManifest, join(output, "src", "DsOperationMap.cs"));
  }
  await cp(join(root, "LICENSE"), join(output, "LICENSE"));
  await writeFile(join(output, "services.json"), JSON.stringify({ emitter, services }, null, 2) + "\n");
  // Retain the previous output in the ignored staging directory. Only replace a
  // language's SDK after its entire generation has succeeded.
  const destination = resolve(root, "generated", "clients", language);
  await mkdir(join(root, "generated", "clients"), { recursive: true });
  let synchronizedInPlace = false;
  try { await rename(destination, join(staging, `previous-${language}`)); }
  catch (error) {
    if (error.code === "EPERM" || error.code === "EBUSY") {
      // Windows can temporarily deny directory renames while an IDE or scanner has a file open.
      // Keep the atomic replacement path as the default, but preserve a complete output tree in this case.
      await mirrorDirectory(output, destination);
      synchronizedInPlace = true;
    } else if (error.code !== "ENOENT") {
      throw error;
    }
  }
  if (!synchronizedInPlace) await rename(output, destination);
  console.log(`Generated ${language}: ${destination} (${services.length} services)`);
}

async function emit(entry, emitter, options) {
  check(await compile(NodeHost, entry, { emit: [emitter], options: { [emitter]: options }, outputDir: staging }));
}

async function emitDsManifest() {
  const output = join(staging, "csharp-ds-manifest");
  await emit(join(root, "main.tsp"), "@uigf/typespec-ds", { "emitter-output-dir": output });
  return join(output, "ds-manifest.json");
}

async function createCsharpSource() {
  const directory = join(staging, "csharp-source");
  await cp(join(root, "src"), join(directory, "src"), { recursive: true });
  await cp(join(root, "main.tsp"), join(directory, "main.tsp"));
  await cp(source, join(directory, "client.tsp"));

  for (const entry of await readdir(join(directory, "src"), { withFileTypes: true })) {
    if (!entry.isFile() || !entry.name.endsWith(".tsp")) continue;
    const path = join(directory, "src", entry.name);
    const text = await readFile(path, "utf8");
    const optionalDs = text
      .replaceAll('@header("DS") ds: string', '@header("DS") ds?: string')
      .replace(/(@header\("DS"\)\s*\r?\n\s*)ds: string;/g, "$1ds?: string;");
    if (optionalDs !== text) await writeFile(path, optionalDs);
  }
  return join(directory, "client.tsp");
}

function check(program) {
  const diagnostics = program.diagnostics.filter((d) =>
    d.code !== "@azure-tools/typespec-ts/property-name-normalized");
  logDiagnostics(diagnostics, NodeHost.logSink);
  if (program.hasError()) throw new Error("Client generation failed; see TypeSpec diagnostics above.");
}

async function mirrorDirectory(source, destination) {
  await mkdir(destination, { recursive: true });
  const [sourceEntries, destinationEntries] = await Promise.all([
    readdir(source, { withFileTypes: true }),
    readdir(destination, { withFileTypes: true }),
  ]);
  const sourceByName = new Map(sourceEntries.map((entry) => [entry.name, entry]));

  for (const entry of destinationEntries) {
    if (!sourceByName.has(entry.name)) {
      await rm(join(destination, entry.name), { recursive: true, force: true });
    }
  }

  for (const entry of sourceEntries) {
    const sourcePath = join(source, entry.name);
    const destinationPath = join(destination, entry.name);
    if (entry.isDirectory()) {
      const destinationEntry = destinationEntries.find((candidate) => candidate.name === entry.name);
      if (destinationEntry && !destinationEntry.isDirectory()) {
        await rm(destinationPath, { force: true });
      }
      await mirrorDirectory(sourcePath, destinationPath);
    } else {
      const destinationEntry = destinationEntries.find((candidate) => candidate.name === entry.name);
      if (destinationEntry?.isDirectory()) {
        await rm(destinationPath, { recursive: true, force: true });
      }
      await cp(sourcePath, destinationPath, { force: true });
    }
  }
}

async function writeCsharpDsOperationMap(manifestPath, outputPath) {
  const manifest = JSON.parse(await readFile(manifestPath, "utf8"));
  const generations = new Map();
  for (const service of manifest.services) {
    for (const operation of service.operations) {
      const generation = operation.generation === "v1" ? "V1" : "V2";
      const previous = generations.get(operation.path);
      if (previous && previous !== generation) {
        throw new Error(`DS generation mismatch for ${operation.path}.`);
      }
      generations.set(operation.path, generation);
    }
  }

  const cases = [...generations.entries()].sort(([left], [right]) => left.localeCompare(right))
    .map(([path, generation]) => `                case "${path}":\n                    generation = DsGeneration.${generation};\n                    return true;`)
    .join("\n");
  const source = `// <auto-generated/>\n\n#nullable enable\n\nnamespace UIGF.Mihoyo\n{\n    internal static class DsOperationMap\n    {\n        internal static bool TryGetGeneration(string path, out DsGeneration generation)\n        {\n            switch (path)\n            {\n${cases}\n                default:\n                    generation = default;\n                    return false;\n            }\n        }\n    }\n}\n`;
  await writeFile(outputPath, source);
}
